// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

namespace Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210720202205_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Domain.Offender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ADD")
                        .HasColumnType("TEXT");

                    b.Property<string>("AKA01")
                        .HasColumnType("TEXT");

                    b.Property<string>("AKA02")
                        .HasColumnType("TEXT");

                    b.Property<string>("AKA03")
                        .HasColumnType("TEXT");

                    b.Property<string>("AKA04")
                        .HasColumnType("TEXT");

                    b.Property<string>("AKA05")
                        .HasColumnType("TEXT");

                    b.Property<string>("AKA06")
                        .HasColumnType("TEXT");

                    b.Property<string>("AOV")
                        .HasColumnType("TEXT");

                    b.Property<string>("BCO")
                        .HasColumnType("TEXT");

                    b.Property<string>("BDA")
                        .HasColumnType("TEXT");

                    b.Property<string>("BHN")
                        .HasColumnType("TEXT");

                    b.Property<string>("BLE")
                        .HasColumnType("TEXT");

                    b.Property<string>("BMA")
                        .HasColumnType("TEXT");

                    b.Property<string>("BMO")
                        .HasColumnType("TEXT");

                    b.Property<string>("BNM")
                        .HasColumnType("TEXT");

                    b.Property<string>("BTY")
                        .HasColumnType("TEXT");

                    b.Property<string>("BYR")
                        .HasColumnType("TEXT");

                    b.Property<string>("CGD")
                        .HasColumnType("TEXT");

                    b.Property<string>("CMC")
                        .HasColumnType("TEXT");

                    b.Property<string>("CON")
                        .HasColumnType("TEXT");

                    b.Property<string>("COU")
                        .HasColumnType("TEXT");

                    b.Property<string>("CRR")
                        .HasColumnType("TEXT");

                    b.Property<string>("CTY")
                        .HasColumnType("TEXT");

                    b.Property<string>("CTZ")
                        .HasColumnType("TEXT");

                    b.Property<string>("DLO")
                        .HasColumnType("TEXT");

                    b.Property<string>("DNA")
                        .HasColumnType("TEXT");

                    b.Property<string>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("EDA")
                        .HasColumnType("TEXT");

                    b.Property<string>("EML")
                        .HasColumnType("TEXT");

                    b.Property<string>("EMP")
                        .HasColumnType("TEXT");

                    b.Property<string>("ERD")
                        .HasColumnType("TEXT");

                    b.Property<string>("ETN")
                        .HasColumnType("TEXT");

                    b.Property<string>("EYE")
                        .HasColumnType("TEXT");

                    b.Property<string>("FBI")
                        .HasColumnType("TEXT");

                    b.Property<string>("FPC")
                        .HasColumnType("TEXT");

                    b.Property<string>("HAI")
                        .HasColumnType("TEXT");

                    b.Property<string>("HGT")
                        .HasColumnType("TEXT");

                    b.Property<string>("HPT")
                        .HasColumnType("TEXT");

                    b.Property<string>("HSP")
                        .HasColumnType("TEXT");

                    b.Property<string>("HUL")
                        .HasColumnType("TEXT");

                    b.Property<string>("IID")
                        .HasColumnType("TEXT");

                    b.Property<string>("JUV")
                        .HasColumnType("TEXT");

                    b.Property<string>("LIC")
                        .HasColumnType("TEXT");

                    b.Property<string>("LIS")
                        .HasColumnType("TEXT");

                    b.Property<string>("LIT")
                        .HasColumnType("TEXT");

                    b.Property<string>("LIY")
                        .HasColumnType("TEXT");

                    b.Property<string>("LKA")
                        .HasColumnType("TEXT");

                    b.Property<string>("LKI")
                        .HasColumnType("TEXT");

                    b.Property<string>("MIS")
                        .HasColumnType("TEXT");

                    b.Property<string>("MNU")
                        .HasColumnType("TEXT");

                    b.Property<string>("NAM")
                        .HasColumnType("TEXT");

                    b.Property<string>("NIC")
                        .HasColumnType("TEXT");

                    b.Property<string>("OCA")
                        .HasColumnType("TEXT");

                    b.Property<string>("OCP")
                        .HasColumnType("TEXT");

                    b.Property<string>("OFS")
                        .HasColumnType("TEXT");

                    b.Property<string>("OLN")
                        .HasColumnType("TEXT");

                    b.Property<string>("OLS")
                        .HasColumnType("TEXT");

                    b.Property<string>("OLY")
                        .HasColumnType("TEXT");

                    b.Property<string>("ORD")
                        .HasColumnType("TEXT");

                    b.Property<string>("ORI")
                        .HasColumnType("TEXT");

                    b.Property<string>("PLC")
                        .HasColumnType("TEXT");

                    b.Property<string>("PLN")
                        .HasColumnType("TEXT");

                    b.Property<string>("PLT")
                        .HasColumnType("TEXT");

                    b.Property<string>("POB")
                        .HasColumnType("TEXT");

                    b.Property<string>("PRO")
                        .HasColumnType("TEXT");

                    b.Property<string>("RAC")
                        .HasColumnType("TEXT");

                    b.Property<string>("REG")
                        .HasColumnType("TEXT");

                    b.Property<string>("RES")
                        .HasColumnType("TEXT");

                    b.Property<string>("REY")
                        .HasColumnType("TEXT");

                    b.Property<string>("ROV")
                        .HasColumnType("TEXT");

                    b.Property<string>("SEX")
                        .HasColumnType("TEXT");

                    b.Property<string>("SHN")
                        .HasColumnType("TEXT");

                    b.Property<string>("SID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SKN")
                        .HasColumnType("TEXT");

                    b.Property<string>("SMT")
                        .HasColumnType("TEXT");

                    b.Property<string>("SNA")
                        .HasColumnType("TEXT");

                    b.Property<string>("SNU")
                        .HasColumnType("TEXT");

                    b.Property<string>("SOC")
                        .HasColumnType("TEXT");

                    b.Property<string>("SOV")
                        .HasColumnType("TEXT");

                    b.Property<string>("STA")
                        .HasColumnType("TEXT");

                    b.Property<string>("SXP")
                        .HasColumnType("TEXT");

                    b.Property<string>("TIR")
                        .HasColumnType("TEXT");

                    b.Property<string>("TNO")
                        .HasColumnType("TEXT");

                    b.Property<string>("TNT")
                        .HasColumnType("TEXT");

                    b.Property<string>("VCO")
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .HasColumnType("TEXT");

                    b.Property<string>("VMA")
                        .HasColumnType("TEXT");

                    b.Property<string>("VMO")
                        .HasColumnType("TEXT");

                    b.Property<string>("VOW")
                        .HasColumnType("TEXT");

                    b.Property<string>("VST")
                        .HasColumnType("TEXT");

                    b.Property<string>("VYR")
                        .HasColumnType("TEXT");

                    b.Property<string>("WGT")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZIP")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Offenders");
                });
#pragma warning restore 612, 618
        }
    }
}
